const URL = "https://gatherly-dyco.onrender.com";

export const REGISTER = `${URL}/api/users/register`;
export const LOGIN = `${URL}/api/users/login`;
export const LOGOUT = `${URL}/api/user/logout`;
export const USER_INFO_UPDATE = `${URL}/api/users/updateUser`;
export const CHANGE_PASSWORD = `${URL}/api/users/changePassword`;
export const CREATE_EVENT = `${URL}/api/events/createEvent`;
export const UPDATE_EVENT = `${URL}/api/events/updateEvent`;
export const USER_LIST = `${URL}/api/events/userList`;
// export const DELETE_BOOKING = `${URL}/api/booking/deleteBooking`;
export const ALL_EVENT = `${URL}/api/events/allEvent`;
export const FIND_EVENT_BY_ID = `${URL}/api/events`;
export const CREATE_BOOKING = `${URL}/api/booking/eventBooking`;
export const VERIFY_PAYMENT = `${URL}/api/booking/verifyPayment`;
export const CHECKISREGISTER = `${URL}/api/booking/alreadyRegister`;
export const TOTALCREATEDEVENT = `${URL}/api/profile/totalCreatedEvent`;
export const TOTALREGISTEREVENT = `${URL}/api/profile/totalRegisterEvent`;
export const DELETE_EVENT = `${URL}/api/profile`;